services:
  vaultwarden:
    image: vaultwarden/server:1.36.0
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data/
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
    external: true
