networks:
  proxynet:
    name: proxynet
 
services:
  proxy:
    image: jc21/nginx-proxy-manager:2.15.1
    container_name: proxy-prod
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data/data:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - proxynet
